### ISSUE TITLE
Fatal error: Call to protected method 

### ISSUE THREAD

**Issue by errand** [bircher/drupal-google_analytics_counter#2]
Hello!
I'm getting the error 

Fatal error: Call to protected method Drupal\google_analytics_counter\GoogleAnalyticsCounterCommon::newGaFeed() from context 'Drupal\google_analytics_counter\Form\GoogleAnalyticsCounterAdminAuthForm' in F:\OpenServer\domains\drupal8.hom\modules\drupal-google_analytics_counter\src\Form\GoogleAnalyticsCounterAdminAuthForm.php on line 30

I'm using clean Minimal 8.2.7 install on local server

**Comment by bircher** [comment]
Thanks for reporting and thanks for the pull request!
